DownloadPlatform=Telegram
# SQMP3 | DeezerMusicBot | MusicsHuntersbot
DownloadBot=DeezerMusicBot
ResetAccount=False
PlaylistId=17961590701
PlaylistFile=
ExistingListFile=Music_Sean_recurse_download.txt
